# Generated by Django 5.2.3 on 2025-07-07 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_registrationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationtoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
