# Generated by Django 5.2.3 on 2025-07-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_registrationtoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price_at_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
