# Generated by Django 5.2.3 on 2025-07-09 03:41

from django.db import migrations


def fill_orderitem_name_price(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.all():
        item.name = item.menu_item.name
        item.price_at_order = item.menu_item.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_name_orderitem_price_at_order"),
    ]

    operations = [
        migrations.RunPython(fill_orderitem_name_price),
    ]
